#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly=TRUE)

file_size <- as.numeric(args[[1]])

multipart_chunksize <- 8 * 1024 * 1024

while (file_size / multipart_chunksize > 10000) {
  multipart_chunksize <- multipart_chunksize * 2
}

cat(multipart_chunksize / (1024 * 1024))
